"""
Wire a body-rewriting proxy (rolling-context / pii-proxy) into Claude Code via
HTTPS_PROXY — NOT ANTHROPIC_BASE_URL.

Why not ANTHROPIC_BASE_URL: a non-anthropic base URL trips Claude Code's Remote
Control / GrowthBook gate. Routing through HTTPS_PROXY leaves the destination
as api.anthropic.com (gate untouched); the MITM front-end (see mitm_frontend)
terminates TLS with a locally generated CA that Claude Code trusts via
NODE_EXTRA_CA_CERTS, so bodies stay visible.

This module owns the settings.json bookkeeping, which is the fiddly part:

  * NODE_EXTRA_CA_CERTS  — the shared CA cert. Same value for both plugins.
  * HTTPS_PROXY          — single-valued, so only the *outermost* proxy's MITM
                           owns it; the other chains behind it over plain HTTP
                           via its <PLUGIN>_UPSTREAM key (core -> core -> api).

Two plugins wiring independently converge on one consistent chain. The same
file ships verbatim in both plugins; the plugin identifies itself with --name.
"""
from __future__ import annotations

import argparse
import json
import os
from urllib.parse import urlparse

# Pure stdlib on purpose: this runs under whichever python a hook happens to use
# (pii-proxy's venv, a bare system python), so it must not import cryptography.
# The CA file itself is generated by the proxy server on startup (mitm_frontend);
# here we only need its deterministic path.
CA_CERT_NAME = "ca-cert.pem"

DEFAULT_API = "https://api.anthropic.com"
LOOPBACK = ("127.0.0.1", "localhost", "::1", "0.0.0.0")

# The full family. Ports are the built-in defaults; a running instance may
# override via env, which is reflected into settings.json by the hook, so we
# read the effective value from the env block when present.
PROXIES = {
    "rolling-context": {
        "core": ("ROLLING_CONTEXT_PORT", 5588),
        "mitm": ("ROLLING_CONTEXT_MITM_PORT", 5590),
        "upstream": "ROLLING_CONTEXT_UPSTREAM",
        "defaults": {
            "ROLLING_CONTEXT_PORT": "5588",
            "ROLLING_CONTEXT_TRIGGER": "100000",
            "ROLLING_CONTEXT_TARGET": "40000",
        },
    },
    "pii-proxy": {
        "core": ("PII_PROXY_PORT", 5599),
        "mitm": ("PII_PROXY_MITM_PORT", 5601),
        "upstream": "PII_PROXY_UPSTREAM",
        "defaults": {
            "PII_PROXY_PORT": "5599",
            "PII_PROXY_MIN_SCORE": "0.5",
            "PII_PROXY_MODEL": "openai/privacy-filter",
            "PII_PROXY_WARMUP": "1",
        },
    },
}


def _port(env: dict, spec) -> int:
    key, default = spec
    try:
        return int(env.get(key) or os.environ.get(key) or default)
    except (TypeError, ValueError):
        return default


def _url_port(url: str):
    """Loopback port of `url`, or None if it is not a loopback URL."""
    if not url:
        return None
    try:
        p = urlparse(url if "://" in url else f"http://{url}")
    except ValueError:
        return None
    if (p.hostname or "").lower() not in LOOPBACK:
        return None
    return p.port


def _is_external(url: str, own_ports: set) -> bool:
    """True if `url` is a real endpoint to preserve (not a sibling, not api,
    not one of our own listeners)."""
    if not url:
        return False
    host = (urlparse(url).hostname or "").lower()
    if host in LOOPBACK:
        return _url_port(url) not in own_ports
    return host not in ("api.anthropic.com",) and not host.endswith(".anthropic.com")


def _read_settings(path: str) -> dict:
    try:
        with open(path, encoding="utf-8-sig") as f:
            return json.load(f) or {}
    except FileNotFoundError:
        return {}
    except Exception:
        return {}


def _write_settings(path: str, data: dict) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    body = json.dumps(data, indent=2, ensure_ascii=False) + "\n"
    tmp = path + ".tmp"
    # utf-8 without BOM on purpose: PowerShell 5.1's Set-Content -Encoding UTF8
    # writes a BOM that some readers choke on (rolling-context issues #3/#5).
    with open(tmp, "w", encoding="utf-8") as f:
        f.write(body)
    os.replace(tmp, path)


def wire_env(name: str, env: dict, ca_cert_path: str, notes=None) -> dict:
    """Apply the HTTPS_PROXY / NODE_EXTRA_CA_CERTS / chaining changes to `env`
    in place and return it. Pure dict manipulation so it is unit-testable."""
    def note(msg: str):
        if notes is not None:
            notes.append(msg)

    me = PROXIES[name]
    other_name = next(n for n in PROXIES if n != name)
    other = PROXIES[other_name]

    # --- plugin config defaults + migrations ------------------------------
    for key, value in me.get("defaults", {}).items():
        if key not in env:
            env[key] = value
    # Unset ROLLING_CONTEXT_MODEL = compress with the session's own model
    # (prompt-cache hit). Migrate away the old seeded haiku default.
    if name == "rolling-context" and env.get("ROLLING_CONTEXT_MODEL") == "claude-haiku-4-5-20251001":
        env.pop("ROLLING_CONTEXT_MODEL", None)
        note("migrated away pinned ROLLING_CONTEXT_MODEL (uses session model)")

    my_core_port = _port(env, me["core"])
    my_mitm_port = _port(env, me["mitm"])
    other_mitm_port = _port(env, other["mitm"])
    other_core_port = _port(env, other["core"])

    my_core_url = f"http://127.0.0.1:{my_core_port}"
    my_mitm_url = f"http://127.0.0.1:{my_mitm_port}"
    other_core_url = f"http://127.0.0.1:{other_core_port}"
    own_ports = {my_core_port, my_mitm_port}

    # --- NODE_EXTRA_CA_CERTS: shared, must include our CA -----------------
    existing_ca = (env.get("NODE_EXTRA_CA_CERTS") or "").strip()
    if not existing_ca:
        env["NODE_EXTRA_CA_CERTS"] = ca_cert_path
        note(f"NODE_EXTRA_CA_CERTS = {ca_cert_path}")
    elif os.path.abspath(existing_ca) == os.path.abspath(ca_cert_path):
        pass  # already ours (or the shared bundle) — nothing to do
    else:
        # A pre-existing CA (corporate, or the sibling already built a bundle).
        # Node reads exactly one file, but a PEM file may hold many certs, so we
        # concatenate into a bundle next to our CA and point at that. Idempotent.
        bundle = os.path.join(os.path.dirname(ca_cert_path), "node-ca-bundle.pem")
        try:
            parts = []
            for p in (existing_ca, ca_cert_path):
                with open(p, "r", encoding="utf-8") as f:
                    parts.append(f.read().strip())
            with open(bundle, "w", encoding="utf-8") as f:
                f.write("\n".join(parts) + "\n")
            env.setdefault("PROXY_CA_ORIGINAL_NEC", existing_ca)
            env["NODE_EXTRA_CA_CERTS"] = bundle
            note(f"NODE_EXTRA_CA_CERTS = {bundle} (bundled with existing CA)")
        except OSError as e:
            note(f"WARNING: could not bundle existing CA ({e}); leaving it and "
                 "appending ours would be unsafe — HTTPS interception may fail")

    # --- ANTHROPIC_BASE_URL handling -------------------------------------
    # We never set it (that is what trips the gate). Two cases to handle:
    #   * points at us  -> stale from an old version; remove it.
    #   * a real gateway (GLM/Z.ai, DeepSeek, OpenRouter, corporate) -> leave it
    #     as the host Claude Code talks to, and make it our terminal upstream so
    #     the MITM intercepts that host and forwards there. That host's base_url
    #     already trips the gate by the user's own choice, so there is nothing to
    #     avoid — only body rewriting to preserve.
    base = (env.get("ANTHROPIC_BASE_URL") or "").strip()
    base_host = (urlparse(base).hostname or "").lower() if base else ""
    terminal = DEFAULT_API
    if _url_port(base) in own_ports:
        env.pop("ANTHROPIC_BASE_URL", None)
        note("removed stale ANTHROPIC_BASE_URL (we route via HTTPS_PROXY now)")
    elif base_host and base_host not in LOOPBACK and not (
        base_host == "api.anthropic.com" or base_host.endswith(".anthropic.com")
    ):
        terminal = base
        note(f"custom endpoint {base} kept; intercepting and forwarding there")

    # Fall back to a manually-set external upstream if base_url gave none.
    if terminal == DEFAULT_API:
        existing_up = (env.get(me["upstream"]) or "").strip()
        if _is_external(existing_up, own_ports | {other_core_port, other_mitm_port}):
            terminal = existing_up

    # --- HTTPS_PROXY ownership + core chaining ----------------------------
    cur = (env.get("HTTPS_PROXY") or "").strip()
    cur_port = _url_port(cur)

    if cur and cur_port is None:
        # A real (non-loopback) proxy is already configured — a corporate hop.
        # Hijacking it risks breaking the user's network. Leave it and warn:
        # interception is off until they wire us in front by hand.
        note(f"WARNING: HTTPS_PROXY is an external proxy ({cur}); leaving it "
             "untouched. This plugin will not intercept until configured manually.")
        return env

    if cur_port == other_mitm_port:
        # The sibling owns the slot and is outermost. Become the inner hop:
        # sibling.core -> my.core -> (preserved external | api).
        prev = (env.get(other["upstream"]) or "").strip()
        if _is_external(prev, {other_core_port, other_mitm_port}):
            # Preserve a corporate endpoint at the innermost hop.
            if not _is_external((env.get(me["upstream"]) or ""), own_ports):
                env[me["upstream"]] = prev
        env[other["upstream"]] = my_core_url
        if not _is_external((env.get(me["upstream"]) or ""), own_ports):
            env[me["upstream"]] = terminal
        note(f"chained behind {other_name}: {other['upstream']} -> {my_core_url}")
        return env

    # Otherwise (unset / api / already mine): I own HTTPS_PROXY.
    env["HTTPS_PROXY"] = my_mitm_url
    my_up = (env.get(me["upstream"]) or "").strip()
    if _url_port(my_up) == other_core_port:
        # Sibling core is chained behind me — keep it.
        note(f"HTTPS_PROXY = {my_mitm_url} (upstream kept: {my_up})")
    else:
        env[me["upstream"]] = terminal
        note(f"HTTPS_PROXY = {my_mitm_url} (upstream -> {terminal})")
    return env


def unwire_env(name: str, env: dict, ca_cert_path: str, notes=None) -> dict:
    """Reverse wire_env: remove this plugin from the chain, repairing it so the
    sibling (if still present) keeps working. Pure dict manipulation."""
    def note(msg: str):
        if notes is not None:
            notes.append(msg)

    me = PROXIES[name]
    other_name = next(n for n in PROXIES if n != name)
    other = PROXIES[other_name]

    my_core_port = _port(env, me["core"])
    my_mitm_port = _port(env, me["mitm"])
    other_mitm_port = _port(env, other["mitm"])
    other_core_port = _port(env, other["core"])
    my_mitm_url = f"http://127.0.0.1:{my_mitm_port}"
    other_mitm_url = f"http://127.0.0.1:{other_mitm_port}"
    other_core_url = f"http://127.0.0.1:{other_core_port}"

    my_upstream = (env.get(me["upstream"]) or "").strip()
    cur = (env.get("HTTPS_PROXY") or "").strip()
    sibling_in_chain = (
        _url_port(cur) == other_mitm_port
        or _url_port(my_upstream) == other_core_port
    )

    if _url_port(cur) == my_mitm_port:
        # I own HTTPS_PROXY. If the sibling is chained behind me, promote it to
        # outermost; otherwise the entrypoint goes away entirely.
        if _url_port(my_upstream) == other_core_port:
            env["HTTPS_PROXY"] = other_mitm_url
            note(f"HTTPS_PROXY -> {other_mitm_url} ({other_name} promoted to outermost)")
        else:
            env.pop("HTTPS_PROXY", None)
            note("removed HTTPS_PROXY")
    elif _url_port(cur) == other_mitm_port:
        # Sibling is outermost; I am the inner hop. Bypass me: point the
        # sibling's core straight at what I was forwarding to.
        env[other["upstream"]] = my_upstream or DEFAULT_API
        note(f"{other['upstream']} -> {my_upstream or DEFAULT_API} (bypassing {name})")

    env.pop(me["upstream"], None)

    # NODE_EXTRA_CA_CERTS is shared — only drop it when the sibling is gone too.
    nec = (env.get("NODE_EXTRA_CA_CERTS") or "").strip()
    if not sibling_in_chain and nec and os.path.abspath(nec) == os.path.abspath(ca_cert_path):
        env.pop("NODE_EXTRA_CA_CERTS", None)
        orig = env.pop("PROXY_CA_ORIGINAL_NEC", None)
        if orig:
            env["NODE_EXTRA_CA_CERTS"] = orig
            note(f"restored NODE_EXTRA_CA_CERTS = {orig}")
        else:
            note("removed NODE_EXTRA_CA_CERTS")
    return env


def _reaches_via_our_mitm(env: dict, my_mitm_port: int) -> bool:
    """True if this env sends api.anthropic.com through our MITM AND carries a
    CA — i.e. a process launched with it can complete the intercepted TLS.

    The distinction that matters for issue #12: NODE_EXTRA_CA_CERTS is read once,
    at process launch. A running session that lacked it cannot be made to trust
    the MITM cert by a later settings rewrite — its every request would reset.
    """
    if not (env.get("NODE_EXTRA_CA_CERTS") or "").strip():
        return False
    return _url_port((env.get("HTTPS_PROXY") or "").strip()) == my_mitm_port


def _established_client_sockets(ports) -> int:
    """Count ESTABLISHED TCP connections whose local side is one of `ports`.

    A running session talking to us shows up as ESTABLISHED on our listening
    port. Self-contained (this module stays import-light) mirror of the same
    check in probe.py. Returns 0 when netstat/ss is unavailable — never blocks
    wiring on a machine we cannot inspect.
    """
    import re
    import subprocess

    want = {str(p) for p in ports}
    out = None
    for cmd in (["netstat", "-an"], ["ss", "-tan"]):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=5)
            if r.stdout:
                out = r.stdout
                break
        except Exception:
            continue
    if not out:
        return 0
    n = 0
    for line in out.splitlines():
        if "ESTAB" not in line.upper():
            continue
        for col in line.split():
            m = re.search(r"[:.](\d+)$", col)
            if m:
                if m.group(1) in want:
                    n += 1
                break
    return n


def main() -> int:
    ap = argparse.ArgumentParser(description="Wire a body-rewriting proxy into Claude Code via HTTPS_PROXY")
    ap.add_argument("--name", required=True, choices=list(PROXIES))
    ap.add_argument("--settings", default=os.path.join(os.path.expanduser("~"), ".claude", "settings.json"))
    ap.add_argument("--ca-dir", default=os.path.join(os.path.expanduser("~"), ".claude", "proxy-ca"))
    ap.add_argument("--unwire", action="store_true", help="remove this plugin from the chain")
    ap.add_argument("--quiet", action="store_true")
    args = ap.parse_args()

    ca_cert_path = os.path.join(args.ca_dir, CA_CERT_NAME)

    settings = _read_settings(args.settings)
    env = settings.get("env")
    if not isinstance(env, dict):
        env = {}
    settings["env"] = env

    notes: list[str] = []
    if args.unwire:
        unwire_env(args.name, env, ca_cert_path, notes)
        _write_settings(args.settings, settings)
    else:
        import copy

        me = PROXIES[args.name]
        my_mitm_port = _port(env, me["mitm"])
        my_core_port = _port(env, me["core"])

        before = copy.deepcopy(env)
        after = wire_env(args.name, env, ca_cert_path, notes)

        # Issue #12: this rewrite would flip the transport onto our MITM, but the
        # env before it could not reach us that way. Claude Code live-reloads the
        # settings `env` into ALREADY-RUNNING sessions; those processes fixed
        # their CA trust at launch and cannot start trusting the MITM cert now,
        # so each would reset on every request until restarted. If any session is
        # currently established on our ports, defer the flip to a later session
        # start when nothing is live to be stranded. New sessions keep working on
        # the transport already in the file (the core port still listens).
        flip = _reaches_via_our_mitm(after, my_mitm_port) and not _reaches_via_our_mitm(before, my_mitm_port)
        forced = (os.environ.get("ROLLING_CONTEXT_FORCE_WIRE") or "").strip() not in ("", "0")
        if flip and not forced:
            live = _established_client_sockets({my_core_port, my_mitm_port})
            if live > 0:
                settings["env"] = before
                notes = [
                    f"DEFERRED transport change: {live} running session(s) are "
                    f"connected on ports {my_core_port}/{my_mitm_port}. Flipping "
                    "them onto the MITM now would strand them (their CA trust is "
                    "fixed at launch) — they would ECONNRESET every request until "
                    "restarted. Left settings.json unchanged; the flip happens on "
                    "a later session start once they have drained. Set "
                    "ROLLING_CONTEXT_FORCE_WIRE=1 to override, then restart or "
                    "--resume any old sessions.",
                ]
                _write_settings(args.settings, settings)
                if not args.quiet:
                    for n in notes:
                        print(f"  {n}")
                return 0
        _write_settings(args.settings, settings)

    if not args.quiet:
        for n in notes:
            print(f"  {n}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
